tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_1.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_2.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_3.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_4.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_5.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_6.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_7.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_8.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_9.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_10.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_11.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_12.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_13.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_14.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_15.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_16.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_17.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_18.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_19.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_20.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_21.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_22.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_23.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_24.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_25.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_26.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_27.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_28.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_29.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_30.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_31.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_32.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_33.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_34.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_35.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_36.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_37.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_38.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_39.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:creator_list_40.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:omit.name"} ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:qq_group.name" } ] }
tellraw @s { "rawtext" : [ { "translate" : "text.dec:thanks.name" } ] }