title @s[scores={wbxlgj=0}] actionbar §6蓄力:§4□□□□□□□□
title @s[scores={wbxlgj=1}] actionbar §6蓄力:§4■□□□□□□□
title @s[scores={wbxlgj=2}] actionbar §6蓄力:§4■■□□□□□□
title @s[scores={wbxlgj=3}] actionbar §6蓄力:§4■■■□□□□□
title @s[scores={wbxlgj=4}] actionbar §6蓄力:§4■■■■□□□□
title @s[scores={wbxlgj=5}] actionbar §6蓄力:§4■■■■■□□□
title @s[scores={wbxlgj=6}] actionbar §6蓄力:§4■■■■■■□□
title @s[scores={wbxlgj=7}] actionbar §6蓄力:§4■■■■■■■□
title @s[scores={wbxlgj=8}] actionbar §6蓄力:§4■■■■■■■■
title @s[scores={wbxlgj=9}] actionbar §6蓄力:§a□□□□□□□□
title @s[scores={wbxlgj=10}] actionbar §6蓄力:§a■□□□□□□□
title @s[scores={wbxlgj=11}] actionbar §6蓄力:§a■■□□□□□□
title @s[scores={wbxlgj=12}] actionbar §6蓄力:§a■■■□□□□□
title @s[scores={wbxlgj=13}] actionbar §6蓄力:§a■■■■□□□□
title @s[scores={wbxlgj=14}] actionbar §6蓄力:§a■■■■■□□□
title @s[scores={wbxlgj=15}] actionbar §6蓄力:§a■■■■■■□□
title @s[scores={wbxlgj=16}] actionbar §6蓄力:§a■■■■■■■□
title @s[scores={wbxlgj=17}] actionbar §6蓄力:§a■■■■■■■■