effect @s[scores={dabsorption=10}] absorption 10 10
effect @s[scores={dabsorption=2}] absorption 10 2
effect @s[scores={dabsorption=3}] absorption 10 3
effect @s[scores={dabsorption=4}] absorption 10 4
effect @s[scores={dabsorption=5}] absorption 10 5
effect @s[scores={dabsorption=6}] absorption 10 6
effect @s[scores={dabsorption=7}] absorption 10 7
effect @s[scores={dabsorption=8}] absorption 10 8
effect @s[scores={dabsorption=9}] absorption 10 9
effect @s[scores={dabsorption=0}] absorption 10 0
