##近似八角形
summon dec:snow_energy_fuse ~~~
summon dec:snow_energy_fuse ~1~~
summon dec:snow_energy_fuse ~~~1
summon dec:snow_energy_fuse ~-1~~
summon dec:snow_energy_fuse ~~~-1
summon dec:snow_energy_fuse ~1~~1
summon dec:snow_energy_fuse ~-1~~-1
summon dec:snow_energy_fuse ~1~~-1
summon dec:snow_energy_fuse ~-1~~1
summon dec:snow_energy_fuse ~2~~
summon dec:snow_energy_fuse ~-2~~
summon dec:snow_energy_fuse ~~~2
summon dec:snow_energy_fuse ~~~-2

summon dec:snow_energy_fuse ~5~~
summon dec:snow_energy_fuse ~-5~~
summon dec:snow_energy_fuse ~~~5
summon dec:snow_energy_fuse ~~~-5
summon dec:snow_energy_fuse ~4~~1
summon dec:snow_energy_fuse ~4~~-1
summon dec:snow_energy_fuse ~-4~~1
summon dec:snow_energy_fuse ~-4~~-1
summon dec:snow_energy_fuse ~1~~4
summon dec:snow_energy_fuse ~1~~-4
summon dec:snow_energy_fuse ~-1~~4
summon dec:snow_energy_fuse ~-1~~-4
summon dec:snow_energy_fuse ~3~~2
summon dec:snow_energy_fuse ~3~~-2
summon dec:snow_energy_fuse ~-3~~2
summon dec:snow_energy_fuse ~-3~~-2
summon dec:snow_energy_fuse ~2~~3
summon dec:snow_energy_fuse ~2~~-3
summon dec:snow_energy_fuse ~-2~~3
summon dec:snow_energy_fuse ~-2~~-3

summon dec:snow_energy_fuse ~4~~3
summon dec:snow_energy_fuse ~4~~-3
summon dec:snow_energy_fuse ~-4~~3
summon dec:snow_energy_fuse ~-4~~-3
summon dec:snow_energy_fuse ~3~~4
summon dec:snow_energy_fuse ~3~~-4
summon dec:snow_energy_fuse ~-3~~4
summon dec:snow_energy_fuse ~-3~~-4
summon dec:snow_energy_fuse ~4~~4
summon dec:snow_energy_fuse ~4~~-4
summon dec:snow_energy_fuse ~-4~~4
summon dec:snow_energy_fuse ~-4~~-4