execute if block ~0.4~~ stone run setblock ~0.4~~ air [] destroy
execute if block ~-0.4~~ stone run setblock ~-0.4~~ air [] destroy
execute if block ~~~0.4 stone run setblock ~~~0.4 air [] destroy
execute if block ~~~-0.4 stone run setblock ~~~-0.4 air [] destroy
execute if block ~0.4~~0.4 stone run setblock ~0.4~~0.4 air [] destroy
execute if block ~0.4~~-0.4 stone run setblock ~0.4~~-0.4 air [] destroy
execute if block ~-0.4~~0.4 stone run setblock ~-0.4~~0.4 air [] destroy
execute if block ~-0.4~~-0.4 stone run setblock ~-0.4~~-0.4 air [] destroy
execute if block ~0.4~1~ stone run setblock ~0.4~1~ air [] destroy
execute if block ~-0.4~1~ stone run setblock ~-0.4~1~ air [] destroy
execute if block ~~1~0.4 stone run setblock ~~1~0.4 air [] destroy
execute if block ~~1~-0.4 stone run setblock ~~1~-0.4 air [] destroy
execute if block ~0.4~1~0.4 stone run setblock ~0.4~1~0.4 air [] destroy
execute if block ~0.4~1~-0.4 stone run setblock ~0.4~1~-0.4 air [] destroy
execute if block ~-0.4~1~0.4 stone run setblock ~-0.4~1~0.4 air [] destroy
execute if block ~-0.4~1~-0.4 stone run setblock ~-0.4~1~-0.4 air [] destroy

execute if block ~0.4~~ sandstone run setblock ~0.4~~ air [] destroy
execute if block ~-0.4~~ sandstone run setblock ~-0.4~~ air [] destroy
execute if block ~~~0.4 sandstone run setblock ~~~0.4 air [] destroy
execute if block ~~~-0.4 sandstone run setblock ~~~-0.4 air [] destroy
execute if block ~0.4~~0.4 sandstone run setblock ~0.4~~0.4 air [] destroy
execute if block ~0.4~~-0.4 sandstone run setblock ~0.4~~-0.4 air [] destroy
execute if block ~-0.4~~0.4 sandstone run setblock ~-0.4~~0.4 air [] destroy
execute if block ~-0.4~~-0.4 sandstone run setblock ~-0.4~~-0.4 air [] destroy
execute if block ~0.4~1~ sandstone run setblock ~0.4~1~ air [] destroy
execute if block ~-0.4~1~ sandstone run setblock ~-0.4~1~ air [] destroy
execute if block ~~1~0.4 sandstone run setblock ~~1~0.4 air [] destroy
execute if block ~~1~-0.4 sandstone run setblock ~~1~-0.4 air [] destroy
execute if block ~0.4~1~0.4 sandstone run setblock ~0.4~1~0.4 air [] destroy
execute if block ~0.4~1~-0.4 sandstone run setblock ~0.4~1~-0.4 air [] destroy
execute if block ~-0.4~1~0.4 sandstone run setblock ~-0.4~1~0.4 air [] destroy
execute if block ~-0.4~1~-0.4 sandstone run setblock ~-0.4~1~-0.4 air [] destroy

execute if block ~0.4~~ red_sandstone run setblock ~0.4~~ air [] destroy
execute if block ~-0.4~~ red_sandstone run setblock ~-0.4~~ air [] destroy
execute if block ~~~0.4 red_sandstone run setblock ~~~0.4 air [] destroy
execute if block ~~~-0.4 red_sandstone run setblock ~~~-0.4 air [] destroy
execute if block ~0.4~~0.4 red_sandstone run setblock ~0.4~~0.4 air [] destroy
execute if block ~0.4~~-0.4 red_sandstone run setblock ~0.4~~-0.4 air [] destroy
execute if block ~-0.4~~0.4 red_sandstone run setblock ~-0.4~~0.4 air [] destroy
execute if block ~-0.4~~-0.4 red_sandstone run setblock ~-0.4~~-0.4 air [] destroy
execute if block ~0.4~1~ red_sandstone run setblock ~0.4~1~ air [] destroy
execute if block ~-0.4~1~ red_sandstone run setblock ~-0.4~1~ air [] destroy
execute if block ~~1~0.4 red_sandstone run setblock ~~1~0.4 air [] destroy
execute if block ~~1~-0.4 red_sandstone run setblock ~~1~-0.4 air [] destroy
execute if block ~0.4~1~0.4 red_sandstone run setblock ~0.4~1~0.4 air [] destroy
execute if block ~0.4~1~-0.4 red_sandstone run setblock ~0.4~1~-0.4 air [] destroy
execute if block ~-0.4~1~0.4 red_sandstone run setblock ~-0.4~1~0.4 air [] destroy
execute if block ~-0.4~1~-0.4 red_sandstone run setblock ~-0.4~1~-0.4 air [] destroy

execute if block ~0.4~~ cobblestone run setblock ~0.4~~ air [] destroy
execute if block ~-0.4~~ cobblestone run setblock ~-0.4~~ air [] destroy
execute if block ~~~0.4 cobblestone run setblock ~~~0.4 air [] destroy
execute if block ~~~-0.4 cobblestone run setblock ~~~-0.4 air [] destroy
execute if block ~0.4~~0.4 cobblestone run setblock ~0.4~~0.4 air [] destroy
execute if block ~0.4~~-0.4 cobblestone run setblock ~0.4~~-0.4 air [] destroy
execute if block ~-0.4~~0.4 cobblestone run setblock ~-0.4~~0.4 air [] destroy
execute if block ~-0.4~~-0.4 cobblestone run setblock ~-0.4~~-0.4 air [] destroy
execute if block ~0.4~1~ cobblestone run setblock ~0.4~1~ air [] destroy
execute if block ~-0.4~1~ cobblestone run setblock ~-0.4~1~ air [] destroy
execute if block ~~1~0.4 cobblestone run setblock ~~1~0.4 air [] destroy
execute if block ~~1~-0.4 cobblestone run setblock ~~1~-0.4 air [] destroy
execute if block ~0.4~1~0.4 cobblestone run setblock ~0.4~1~0.4 air [] destroy
execute if block ~0.4~1~-0.4 cobblestone run setblock ~0.4~1~-0.4 air [] destroy
execute if block ~-0.4~1~0.4 cobblestone run setblock ~-0.4~1~0.4 air [] destroy
execute if block ~-0.4~1~-0.4 cobblestone run setblock ~-0.4~1~-0.4 air [] destroy