execute positioned as @s run detect ~ ~ ~ water -1 execute positioned as @s run detect ~+1 ~+1 ~ wb:block_magic_equipment -1 execute positioned as @s run detect ~-1 ~+1 ~ wb:block_magic_equipment -1 execute positioned as @s run detect ~ ~+1 ~+1 wb:block_magic_equipment -1 execute positioned as @s run detect ~ ~+1 ~-1 wb:block_magic_equipment -1 execute positioned as @s run detect ~+1 ~+1 ~+1 wb:block_magic_barrier -1 execute positioned as @s run detect ~-1 ~+1 ~+1 wb:block_magic_barrier -1 execute positioned as @s run detect ~+1 ~+1 ~-1 wb:block_magic_barrier -1 execute positioned as @s run detect ~-1 ~+1 ~-1 wb:block_magic_barrier -1 tag @s add wbptboss
execute positioned as @s[tag=wbptboss] run fill ~+1 ~+1 ~+1 ~-1 ~+1 ~-1 air 0 replace
execute positioned as @s[tag=wbptboss] run setblock ~+2 ~+1 ~+1 wb:block_magic_barrier 0 replace
execute positioned as @s[tag=wbptboss] run setblock ~+2 ~+1 ~-1 wb:block_magic_barrier 0 replace
execute positioned as @s[tag=wbptboss] run setblock ~-2 ~+1 ~+1 wb:block_magic_barrier 0 replace
execute positioned as @s[tag=wbptboss] run setblock ~-2 ~+1 ~-1 wb:block_magic_barrier 0 replace
execute positioned as @s[tag=wbptboss] run setblock ~+1 ~+1 ~+2 wb:block_magic_equipment 0 replace
execute positioned as @s[tag=wbptboss] run setblock ~-1 ~+1 ~+2 wb:block_magic_equipment 0 replace
execute positioned as @s[tag=wbptboss] run setblock ~+1 ~+1 ~-2 wb:block_magic_equipment 0 replace
execute positioned as @s[tag=wbptboss] run setblock ~-1 ~+1 ~-2 wb:block_magic_equipment 0 replace
execute positioned as @s[tag=wbptboss] run fill ~+1 ~ ~+1 ~-1 ~ ~-1 wb:portal_boss 0 replace
execute positioned as @s[tag=wbptboss] run setblock ~+2 ~+1 ~+2 torch 0 replace
execute positioned as @s[tag=wbptboss] run setblock ~-2 ~+1 ~+2 torch 0 replace
execute positioned as @s[tag=wbptboss] run setblock ~+2 ~+1 ~-2 torch 0 replace
execute positioned as @s[tag=wbptboss] run setblock ~-2 ~+1 ~-2 torch 0 replace
execute positioned as @s[tag=wbptboss] run setblock ~+2 ~+1 ~ stone_slab 0 replace
execute positioned as @s[tag=wbptboss] run setblock ~-2 ~+1 ~ stone_slab 0 replace
execute positioned as @s[tag=wbptboss] run setblock ~ ~+1 ~+2 stone_slab 0 replace
execute positioned as @s[tag=wbptboss] run setblock ~ ~+1 ~-2 stone_slab 0 replace
execute positioned as @s[tag=wbptboss] run summon minecraft:lightning_bolt ~ ~ ~
execute positioned as @s[tag=wbptboss] run tp @s ~ ~+1 ~
execute positioned as @s[tag=wbptboss] run tag @s remove wbptboss