execute as @s at @s if block ~ ~ ~ water -1 run execute as @s at @s if block ~+1 ~+1 ~ wb:block_magic_equipment -1 run execute as @s at @s if block ~-1 ~+1 ~ wb:block_magic_equipment -1 run execute as @s at @s if block ~ ~+1 ~+1 wb:block_magic_equipment -1 run execute as @s at @s if block ~ ~+1 ~-1 wb:block_magic_equipment -1 run execute as @s at @s if block ~+1 ~+1 ~+1 wb:block_magic_barrier -1 run execute as @s at @s if block ~-1 ~+1 ~+1 wb:block_magic_barrier -1 run execute as @s at @s if block ~+1 ~+1 ~-1 wb:block_magic_barrier -1 run execute as @s at @s if block ~-1 ~+1 ~-1 wb:block_magic_barrier -1 run tag @s add wbptboss
execute as @s[tag=wbptboss] at @s run fill ~+1 ~+1 ~+1 ~-1 ~+1 ~-1 air 0 replace
execute as @s[tag=wbptboss] at @s run setblock ~+2 ~+1 ~+1 wb:block_magic_barrier 0 replace
execute as @s[tag=wbptboss] at @s run setblock ~+2 ~+1 ~-1 wb:block_magic_barrier 0 replace
execute as @s[tag=wbptboss] at @s run setblock ~-2 ~+1 ~+1 wb:block_magic_barrier 0 replace
execute as @s[tag=wbptboss] at @s run setblock ~-2 ~+1 ~-1 wb:block_magic_barrier 0 replace
execute as @s[tag=wbptboss] at @s run setblock ~+1 ~+1 ~+2 wb:block_magic_equipment 0 replace
execute as @s[tag=wbptboss] at @s run setblock ~-1 ~+1 ~+2 wb:block_magic_equipment 0 replace
execute as @s[tag=wbptboss] at @s run setblock ~+1 ~+1 ~-2 wb:block_magic_equipment 0 replace
execute as @s[tag=wbptboss] at @s run setblock ~-1 ~+1 ~-2 wb:block_magic_equipment 0 replace
execute as @s[tag=wbptboss] at @s run fill ~+1 ~ ~+1 ~-1 ~ ~-1 wb:portal_boss 0 replace
execute as @s[tag=wbptboss] at @s run setblock ~+2 ~+1 ~+2 torch 0 replace
execute as @s[tag=wbptboss] at @s run setblock ~-2 ~+1 ~+2 torch 0 replace
execute as @s[tag=wbptboss] at @s run setblock ~+2 ~+1 ~-2 torch 0 replace
execute as @s[tag=wbptboss] at @s run setblock ~-2 ~+1 ~-2 torch 0 replace
execute as @s[tag=wbptboss] at @s run setblock ~+2 ~+1 ~ stone_slab 0 replace
execute as @s[tag=wbptboss] at @s run setblock ~-2 ~+1 ~ stone_slab 0 replace
execute as @s[tag=wbptboss] at @s run setblock ~ ~+1 ~+2 stone_slab 0 replace
execute as @s[tag=wbptboss] at @s run setblock ~ ~+1 ~-2 stone_slab 0 replace
execute as @s[tag=wbptboss] at @s run summon minecraft:lightning_bolt ~ ~ ~
execute as @s[tag=wbptboss] at @s run tp @s ~ ~+1 ~
execute as @s[tag=wbptboss] at @s run tag @s remove wbptboss