dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=-1}] wb_base_help0
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=0},tag=!wbstartkeyok] wb_base_talk000
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=0},tag=wbstartkeyok] wb_base_talk0
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=1}] wb_base_talk9
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=2}] wb_base_talk13
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=3}] wb_base_talk19
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=4}] wb_base_talk27
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[tag=wbnearboss,scores={wbnjqzj=0,wbnjqbf=5}] wb_base_talk33
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[tag=!wbnearboss,scores={wbnjqzj=0,wbnjqbf=5}] wb_base_talk34
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=6}] wb_base_talk35
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=7}] wb_base_talk37
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=8}] wb_base_talk49
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[tag=wbnearboss,scores={wbnjqzj=0,wbnjqbf=9}] wb_base_talk57
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[tag=!wbnearboss,scores={wbnjqzj=0,wbnjqbf=9}] wb_base_talk58
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=10}] wb_base_talk59
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=11}] wb_base_talk65
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=12}] wb_base_talk72
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[tag=wbnearboss,scores={wbnjqzj=0,wbnjqbf=13}] wb_base_talk86
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[tag=!wbnearboss,scores={wbnjqzj=0,wbnjqbf=13}] wb_base_talk87
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=14}] wb_base_talk88
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=15}] wb_base_talk90
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[tag=wbnearboss,scores={wbnjqzj=0,wbnjqbf=16}] wb_base_talk101
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[tag=!wbnearboss,scores={wbnjqzj=0,wbnjqbf=16}] wb_base_talk102
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=17}] wb_base_talk103
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=18}] wb_base_talk107
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=19}] wb_base_talk112
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=20}] wb_base_talk120
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=21}] wb_base_talk126
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[tag=wbnearboss,scores={wbnjqzj=0,wbnjqbf=22}] wb_base_talk136
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[tag=!wbnearboss,scores={wbnjqzj=0,wbnjqbf=22}] wb_base_talk137
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=23}] wb_base_talk138
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=24}] wb_base_talk144
dialogue open @e[c=1,type=wb:plot_talk_npc] @s[scores={wbnjqzj=0,wbnjqbf=25}] wb_base_talk148