title @s[scores={wbnldx=0}] actionbar 
title @s[scores={wbnldx=1}] actionbar 
title @s[scores={wbnldx=2}] actionbar 
title @s[scores={wbnldx=3}] actionbar 
title @s[scores={wbnldx=4}] actionbar 
title @s[scores={wbnldx=5}] actionbar 
title @s[scores={wbnldx=6}] actionbar 
title @s[scores={wbnldx=7}] actionbar 
title @s[scores={wbnldx=8}] actionbar 
title @s[scores={wbnldx=9}] actionbar 
title @s[scores={wbnldx=10}] actionbar 
title @s[scores={wbnldx=11}] actionbar 
title @s[scores={wbnldx=12}] actionbar 
title @s[scores={wbnldx=13}] actionbar 
title @s[scores={wbnldx=14}] actionbar 
title @s[scores={wbnldx=15}] actionbar 
title @s[scores={wbnldx=16}] actionbar 
title @s[scores={wbnldx=17}] actionbar 
title @s[scores={wbnldx=18}] actionbar 
title @s[scores={wbnldx=19}] actionbar 
title @s[scores={wbnldx=20}] actionbar 