tag @s[scores={wbef=-100..}] add wbefz
execute positioned as @s[tag=!wbefz] run scoreboard players set @s wbef 0
tag @s remove wbefz
execute positioned as @s[scores={wbef=0}] run function grade/effect2
execute positioned as @s[scores={wbef=0}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力触发成功！"}]}
execute positioned as @s[scores={wbef=0}] run scoreboard players add @s wbef 600
execute positioned as @s[scores={wbef=600}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有600秒"}]}
execute positioned as @s[scores={wbef=599}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有599秒"}]}
execute positioned as @s[scores={wbef=598}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有598秒"}]}
execute positioned as @s[scores={wbef=597}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有597秒"}]}
execute positioned as @s[scores={wbef=596}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有596秒"}]}
execute positioned as @s[scores={wbef=595}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有595秒"}]}
execute positioned as @s[scores={wbef=594}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有594秒"}]}
execute positioned as @s[scores={wbef=593}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有593秒"}]}
execute positioned as @s[scores={wbef=592}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有592秒"}]}
execute positioned as @s[scores={wbef=591}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有591秒"}]}
execute positioned as @s[scores={wbef=590}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有590秒"}]}
execute positioned as @s[scores={wbef=589}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有589秒"}]}
execute positioned as @s[scores={wbef=588}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有588秒"}]}
execute positioned as @s[scores={wbef=587}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有587秒"}]}
execute positioned as @s[scores={wbef=586}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有586秒"}]}
execute positioned as @s[scores={wbef=585}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有585秒"}]}
execute positioned as @s[scores={wbef=584}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有584秒"}]}
execute positioned as @s[scores={wbef=583}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有583秒"}]}
execute positioned as @s[scores={wbef=582}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有582秒"}]}
execute positioned as @s[scores={wbef=581}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有581秒"}]}
execute positioned as @s[scores={wbef=580}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有580秒"}]}
execute positioned as @s[scores={wbef=579}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有579秒"}]}
execute positioned as @s[scores={wbef=578}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有578秒"}]}
execute positioned as @s[scores={wbef=577}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有577秒"}]}
execute positioned as @s[scores={wbef=576}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有576秒"}]}
execute positioned as @s[scores={wbef=575}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有575秒"}]}
execute positioned as @s[scores={wbef=574}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有574秒"}]}
execute positioned as @s[scores={wbef=573}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有573秒"}]}
execute positioned as @s[scores={wbef=572}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有572秒"}]}
execute positioned as @s[scores={wbef=571}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有571秒"}]}
execute positioned as @s[scores={wbef=570}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有570秒"}]}
execute positioned as @s[scores={wbef=569}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有569秒"}]}
execute positioned as @s[scores={wbef=568}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有568秒"}]}
execute positioned as @s[scores={wbef=567}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有567秒"}]}
execute positioned as @s[scores={wbef=566}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有566秒"}]}
execute positioned as @s[scores={wbef=565}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有565秒"}]}
execute positioned as @s[scores={wbef=564}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有564秒"}]}
execute positioned as @s[scores={wbef=563}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有563秒"}]}
execute positioned as @s[scores={wbef=562}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有562秒"}]}
execute positioned as @s[scores={wbef=561}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有561秒"}]}
execute positioned as @s[scores={wbef=560}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有560秒"}]}
execute positioned as @s[scores={wbef=559}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有559秒"}]}
execute positioned as @s[scores={wbef=558}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有558秒"}]}
execute positioned as @s[scores={wbef=557}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有557秒"}]}
execute positioned as @s[scores={wbef=556}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有556秒"}]}
execute positioned as @s[scores={wbef=555}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有555秒"}]}
execute positioned as @s[scores={wbef=554}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有554秒"}]}
execute positioned as @s[scores={wbef=553}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有553秒"}]}
execute positioned as @s[scores={wbef=552}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有552秒"}]}
execute positioned as @s[scores={wbef=551}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有551秒"}]}
execute positioned as @s[scores={wbef=550}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有550秒"}]}
execute positioned as @s[scores={wbef=549}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有549秒"}]}
execute positioned as @s[scores={wbef=548}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有548秒"}]}
execute positioned as @s[scores={wbef=547}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有547秒"}]}
execute positioned as @s[scores={wbef=546}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有546秒"}]}
execute positioned as @s[scores={wbef=545}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有545秒"}]}
execute positioned as @s[scores={wbef=544}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有544秒"}]}
execute positioned as @s[scores={wbef=543}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有543秒"}]}
execute positioned as @s[scores={wbef=542}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有542秒"}]}
execute positioned as @s[scores={wbef=541}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有541秒"}]}
execute positioned as @s[scores={wbef=540}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有540秒"}]}
execute positioned as @s[scores={wbef=539}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有539秒"}]}
execute positioned as @s[scores={wbef=538}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有538秒"}]}
execute positioned as @s[scores={wbef=537}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有537秒"}]}
execute positioned as @s[scores={wbef=536}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有536秒"}]}
execute positioned as @s[scores={wbef=535}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有535秒"}]}
execute positioned as @s[scores={wbef=534}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有534秒"}]}
execute positioned as @s[scores={wbef=533}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有533秒"}]}
execute positioned as @s[scores={wbef=532}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有532秒"}]}
execute positioned as @s[scores={wbef=531}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有531秒"}]}
execute positioned as @s[scores={wbef=530}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有530秒"}]}
execute positioned as @s[scores={wbef=529}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有529秒"}]}
execute positioned as @s[scores={wbef=528}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有528秒"}]}
execute positioned as @s[scores={wbef=527}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有527秒"}]}
execute positioned as @s[scores={wbef=526}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有526秒"}]}
execute positioned as @s[scores={wbef=525}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有525秒"}]}
execute positioned as @s[scores={wbef=524}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有524秒"}]}
execute positioned as @s[scores={wbef=523}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有523秒"}]}
execute positioned as @s[scores={wbef=522}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有522秒"}]}
execute positioned as @s[scores={wbef=521}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有521秒"}]}
execute positioned as @s[scores={wbef=520}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有520秒"}]}
execute positioned as @s[scores={wbef=519}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有519秒"}]}
execute positioned as @s[scores={wbef=518}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有518秒"}]}
execute positioned as @s[scores={wbef=517}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有517秒"}]}
execute positioned as @s[scores={wbef=516}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有516秒"}]}
execute positioned as @s[scores={wbef=515}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有515秒"}]}
execute positioned as @s[scores={wbef=514}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有514秒"}]}
execute positioned as @s[scores={wbef=513}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有513秒"}]}
execute positioned as @s[scores={wbef=512}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有512秒"}]}
execute positioned as @s[scores={wbef=511}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有511秒"}]}
execute positioned as @s[scores={wbef=510}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有510秒"}]}
execute positioned as @s[scores={wbef=509}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有509秒"}]}
execute positioned as @s[scores={wbef=508}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有508秒"}]}
execute positioned as @s[scores={wbef=507}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有507秒"}]}
execute positioned as @s[scores={wbef=506}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有506秒"}]}
execute positioned as @s[scores={wbef=505}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有505秒"}]}
execute positioned as @s[scores={wbef=504}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有504秒"}]}
execute positioned as @s[scores={wbef=503}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有503秒"}]}
execute positioned as @s[scores={wbef=502}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有502秒"}]}
execute positioned as @s[scores={wbef=501}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有501秒"}]}
execute positioned as @s[scores={wbef=500}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有500秒"}]}
execute positioned as @s[scores={wbef=499}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有499秒"}]}
execute positioned as @s[scores={wbef=498}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有498秒"}]}
execute positioned as @s[scores={wbef=497}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有497秒"}]}
execute positioned as @s[scores={wbef=496}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有496秒"}]}
execute positioned as @s[scores={wbef=495}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有495秒"}]}
execute positioned as @s[scores={wbef=494}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有494秒"}]}
execute positioned as @s[scores={wbef=493}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有493秒"}]}
execute positioned as @s[scores={wbef=492}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有492秒"}]}
execute positioned as @s[scores={wbef=491}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有491秒"}]}
execute positioned as @s[scores={wbef=490}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有490秒"}]}
execute positioned as @s[scores={wbef=489}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有489秒"}]}
execute positioned as @s[scores={wbef=488}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有488秒"}]}
execute positioned as @s[scores={wbef=487}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有487秒"}]}
execute positioned as @s[scores={wbef=486}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有486秒"}]}
execute positioned as @s[scores={wbef=485}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有485秒"}]}
execute positioned as @s[scores={wbef=484}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有484秒"}]}
execute positioned as @s[scores={wbef=483}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有483秒"}]}
execute positioned as @s[scores={wbef=482}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有482秒"}]}
execute positioned as @s[scores={wbef=481}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有481秒"}]}
execute positioned as @s[scores={wbef=480}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有480秒"}]}
execute positioned as @s[scores={wbef=479}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有479秒"}]}
execute positioned as @s[scores={wbef=478}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有478秒"}]}
execute positioned as @s[scores={wbef=477}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有477秒"}]}
execute positioned as @s[scores={wbef=476}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有476秒"}]}
execute positioned as @s[scores={wbef=475}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有475秒"}]}
execute positioned as @s[scores={wbef=474}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有474秒"}]}
execute positioned as @s[scores={wbef=473}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有473秒"}]}
execute positioned as @s[scores={wbef=472}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有472秒"}]}
execute positioned as @s[scores={wbef=471}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有471秒"}]}
execute positioned as @s[scores={wbef=470}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有470秒"}]}
execute positioned as @s[scores={wbef=469}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有469秒"}]}
execute positioned as @s[scores={wbef=468}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有468秒"}]}
execute positioned as @s[scores={wbef=467}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有467秒"}]}
execute positioned as @s[scores={wbef=466}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有466秒"}]}
execute positioned as @s[scores={wbef=465}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有465秒"}]}
execute positioned as @s[scores={wbef=464}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有464秒"}]}
execute positioned as @s[scores={wbef=463}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有463秒"}]}
execute positioned as @s[scores={wbef=462}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有462秒"}]}
execute positioned as @s[scores={wbef=461}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有461秒"}]}
execute positioned as @s[scores={wbef=460}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有460秒"}]}
execute positioned as @s[scores={wbef=459}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有459秒"}]}
execute positioned as @s[scores={wbef=458}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有458秒"}]}
execute positioned as @s[scores={wbef=457}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有457秒"}]}
execute positioned as @s[scores={wbef=456}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有456秒"}]}
execute positioned as @s[scores={wbef=455}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有455秒"}]}
execute positioned as @s[scores={wbef=454}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有454秒"}]}
execute positioned as @s[scores={wbef=453}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有453秒"}]}
execute positioned as @s[scores={wbef=452}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有452秒"}]}
execute positioned as @s[scores={wbef=451}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有451秒"}]}
execute positioned as @s[scores={wbef=450}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有450秒"}]}
execute positioned as @s[scores={wbef=449}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有449秒"}]}
execute positioned as @s[scores={wbef=448}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有448秒"}]}
execute positioned as @s[scores={wbef=447}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有447秒"}]}
execute positioned as @s[scores={wbef=446}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有446秒"}]}
execute positioned as @s[scores={wbef=445}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有445秒"}]}
execute positioned as @s[scores={wbef=444}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有444秒"}]}
execute positioned as @s[scores={wbef=443}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有443秒"}]}
execute positioned as @s[scores={wbef=442}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有442秒"}]}
execute positioned as @s[scores={wbef=441}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有441秒"}]}
execute positioned as @s[scores={wbef=440}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有440秒"}]}
execute positioned as @s[scores={wbef=439}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有439秒"}]}
execute positioned as @s[scores={wbef=438}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有438秒"}]}
execute positioned as @s[scores={wbef=437}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有437秒"}]}
execute positioned as @s[scores={wbef=436}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有436秒"}]}
execute positioned as @s[scores={wbef=435}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有435秒"}]}
execute positioned as @s[scores={wbef=434}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有434秒"}]}
execute positioned as @s[scores={wbef=433}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有433秒"}]}
execute positioned as @s[scores={wbef=432}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有432秒"}]}
execute positioned as @s[scores={wbef=431}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有431秒"}]}
execute positioned as @s[scores={wbef=430}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有430秒"}]}
execute positioned as @s[scores={wbef=429}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有429秒"}]}
execute positioned as @s[scores={wbef=428}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有428秒"}]}
execute positioned as @s[scores={wbef=427}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有427秒"}]}
execute positioned as @s[scores={wbef=426}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有426秒"}]}
execute positioned as @s[scores={wbef=425}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有425秒"}]}
execute positioned as @s[scores={wbef=424}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有424秒"}]}
execute positioned as @s[scores={wbef=423}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有423秒"}]}
execute positioned as @s[scores={wbef=422}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有422秒"}]}
execute positioned as @s[scores={wbef=421}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有421秒"}]}
execute positioned as @s[scores={wbef=420}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有420秒"}]}
execute positioned as @s[scores={wbef=419}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有419秒"}]}
execute positioned as @s[scores={wbef=418}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有418秒"}]}
execute positioned as @s[scores={wbef=417}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有417秒"}]}
execute positioned as @s[scores={wbef=416}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有416秒"}]}
execute positioned as @s[scores={wbef=415}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有415秒"}]}
execute positioned as @s[scores={wbef=414}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有414秒"}]}
execute positioned as @s[scores={wbef=413}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有413秒"}]}
execute positioned as @s[scores={wbef=412}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有412秒"}]}
execute positioned as @s[scores={wbef=411}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有411秒"}]}
execute positioned as @s[scores={wbef=410}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有410秒"}]}
execute positioned as @s[scores={wbef=409}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有409秒"}]}
execute positioned as @s[scores={wbef=408}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有408秒"}]}
execute positioned as @s[scores={wbef=407}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有407秒"}]}
execute positioned as @s[scores={wbef=406}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有406秒"}]}
execute positioned as @s[scores={wbef=405}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有405秒"}]}
execute positioned as @s[scores={wbef=404}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有404秒"}]}
execute positioned as @s[scores={wbef=403}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有403秒"}]}
execute positioned as @s[scores={wbef=402}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有402秒"}]}
execute positioned as @s[scores={wbef=401}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有401秒"}]}
execute positioned as @s[scores={wbef=400}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有400秒"}]}
execute positioned as @s[scores={wbef=399}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有399秒"}]}
execute positioned as @s[scores={wbef=398}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有398秒"}]}
execute positioned as @s[scores={wbef=397}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有397秒"}]}
execute positioned as @s[scores={wbef=396}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有396秒"}]}
execute positioned as @s[scores={wbef=395}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有395秒"}]}
execute positioned as @s[scores={wbef=394}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有394秒"}]}
execute positioned as @s[scores={wbef=393}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有393秒"}]}
execute positioned as @s[scores={wbef=392}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有392秒"}]}
execute positioned as @s[scores={wbef=391}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有391秒"}]}
execute positioned as @s[scores={wbef=390}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有390秒"}]}
execute positioned as @s[scores={wbef=389}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有389秒"}]}
execute positioned as @s[scores={wbef=388}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有388秒"}]}
execute positioned as @s[scores={wbef=387}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有387秒"}]}
execute positioned as @s[scores={wbef=386}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有386秒"}]}
execute positioned as @s[scores={wbef=385}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有385秒"}]}
execute positioned as @s[scores={wbef=384}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有384秒"}]}
execute positioned as @s[scores={wbef=383}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有383秒"}]}
execute positioned as @s[scores={wbef=382}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有382秒"}]}
execute positioned as @s[scores={wbef=381}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有381秒"}]}
execute positioned as @s[scores={wbef=380}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有380秒"}]}
execute positioned as @s[scores={wbef=379}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有379秒"}]}
execute positioned as @s[scores={wbef=378}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有378秒"}]}
execute positioned as @s[scores={wbef=377}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有377秒"}]}
execute positioned as @s[scores={wbef=376}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有376秒"}]}
execute positioned as @s[scores={wbef=375}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有375秒"}]}
execute positioned as @s[scores={wbef=374}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有374秒"}]}
execute positioned as @s[scores={wbef=373}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有373秒"}]}
execute positioned as @s[scores={wbef=372}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有372秒"}]}
execute positioned as @s[scores={wbef=371}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有371秒"}]}
execute positioned as @s[scores={wbef=370}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有370秒"}]}
execute positioned as @s[scores={wbef=369}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有369秒"}]}
execute positioned as @s[scores={wbef=368}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有368秒"}]}
execute positioned as @s[scores={wbef=367}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有367秒"}]}
execute positioned as @s[scores={wbef=366}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有366秒"}]}
execute positioned as @s[scores={wbef=365}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有365秒"}]}
execute positioned as @s[scores={wbef=364}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有364秒"}]}
execute positioned as @s[scores={wbef=363}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有363秒"}]}
execute positioned as @s[scores={wbef=362}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有362秒"}]}
execute positioned as @s[scores={wbef=361}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有361秒"}]}
execute positioned as @s[scores={wbef=360}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有360秒"}]}
execute positioned as @s[scores={wbef=359}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有359秒"}]}
execute positioned as @s[scores={wbef=358}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有358秒"}]}
execute positioned as @s[scores={wbef=357}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有357秒"}]}
execute positioned as @s[scores={wbef=356}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有356秒"}]}
execute positioned as @s[scores={wbef=355}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有355秒"}]}
execute positioned as @s[scores={wbef=354}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有354秒"}]}
execute positioned as @s[scores={wbef=353}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有353秒"}]}
execute positioned as @s[scores={wbef=352}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有352秒"}]}
execute positioned as @s[scores={wbef=351}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有351秒"}]}
execute positioned as @s[scores={wbef=350}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有350秒"}]}
execute positioned as @s[scores={wbef=349}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有349秒"}]}
execute positioned as @s[scores={wbef=348}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有348秒"}]}
execute positioned as @s[scores={wbef=347}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有347秒"}]}
execute positioned as @s[scores={wbef=346}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有346秒"}]}
execute positioned as @s[scores={wbef=345}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有345秒"}]}
execute positioned as @s[scores={wbef=344}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有344秒"}]}
execute positioned as @s[scores={wbef=343}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有343秒"}]}
execute positioned as @s[scores={wbef=342}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有342秒"}]}
execute positioned as @s[scores={wbef=341}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有341秒"}]}
execute positioned as @s[scores={wbef=340}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有340秒"}]}
execute positioned as @s[scores={wbef=339}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有339秒"}]}
execute positioned as @s[scores={wbef=338}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有338秒"}]}
execute positioned as @s[scores={wbef=337}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有337秒"}]}
execute positioned as @s[scores={wbef=336}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有336秒"}]}
execute positioned as @s[scores={wbef=335}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有335秒"}]}
execute positioned as @s[scores={wbef=334}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有334秒"}]}
execute positioned as @s[scores={wbef=333}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有333秒"}]}
execute positioned as @s[scores={wbef=332}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有332秒"}]}
execute positioned as @s[scores={wbef=331}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有331秒"}]}
execute positioned as @s[scores={wbef=330}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有330秒"}]}
execute positioned as @s[scores={wbef=329}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有329秒"}]}
execute positioned as @s[scores={wbef=328}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有328秒"}]}
execute positioned as @s[scores={wbef=327}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有327秒"}]}
execute positioned as @s[scores={wbef=326}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有326秒"}]}
execute positioned as @s[scores={wbef=325}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有325秒"}]}
execute positioned as @s[scores={wbef=324}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有324秒"}]}
execute positioned as @s[scores={wbef=323}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有323秒"}]}
execute positioned as @s[scores={wbef=322}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有322秒"}]}
execute positioned as @s[scores={wbef=321}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有321秒"}]}
execute positioned as @s[scores={wbef=320}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有320秒"}]}
execute positioned as @s[scores={wbef=319}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有319秒"}]}
execute positioned as @s[scores={wbef=318}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有318秒"}]}
execute positioned as @s[scores={wbef=317}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有317秒"}]}
execute positioned as @s[scores={wbef=316}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有316秒"}]}
execute positioned as @s[scores={wbef=315}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有315秒"}]}
execute positioned as @s[scores={wbef=314}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有314秒"}]}
execute positioned as @s[scores={wbef=313}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有313秒"}]}
execute positioned as @s[scores={wbef=312}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有312秒"}]}
execute positioned as @s[scores={wbef=311}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有311秒"}]}
execute positioned as @s[scores={wbef=310}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有310秒"}]}
execute positioned as @s[scores={wbef=309}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有309秒"}]}
execute positioned as @s[scores={wbef=308}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有308秒"}]}
execute positioned as @s[scores={wbef=307}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有307秒"}]}
execute positioned as @s[scores={wbef=306}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有306秒"}]}
execute positioned as @s[scores={wbef=305}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有305秒"}]}
execute positioned as @s[scores={wbef=304}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有304秒"}]}
execute positioned as @s[scores={wbef=303}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有303秒"}]}
execute positioned as @s[scores={wbef=302}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有302秒"}]}
execute positioned as @s[scores={wbef=301}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有301秒"}]}
execute positioned as @s[scores={wbef=300}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有300秒"}]}
execute positioned as @s[scores={wbef=299}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有299秒"}]}
execute positioned as @s[scores={wbef=298}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有298秒"}]}
execute positioned as @s[scores={wbef=297}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有297秒"}]}
execute positioned as @s[scores={wbef=296}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有296秒"}]}
execute positioned as @s[scores={wbef=295}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有295秒"}]}
execute positioned as @s[scores={wbef=294}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有294秒"}]}
execute positioned as @s[scores={wbef=293}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有293秒"}]}
execute positioned as @s[scores={wbef=292}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有292秒"}]}
execute positioned as @s[scores={wbef=291}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有291秒"}]}
execute positioned as @s[scores={wbef=290}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有290秒"}]}
execute positioned as @s[scores={wbef=289}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有289秒"}]}
execute positioned as @s[scores={wbef=288}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有288秒"}]}
execute positioned as @s[scores={wbef=287}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有287秒"}]}
execute positioned as @s[scores={wbef=286}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有286秒"}]}
execute positioned as @s[scores={wbef=285}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有285秒"}]}
execute positioned as @s[scores={wbef=284}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有284秒"}]}
execute positioned as @s[scores={wbef=283}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有283秒"}]}
execute positioned as @s[scores={wbef=282}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有282秒"}]}
execute positioned as @s[scores={wbef=281}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有281秒"}]}
execute positioned as @s[scores={wbef=280}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有280秒"}]}
execute positioned as @s[scores={wbef=279}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有279秒"}]}
execute positioned as @s[scores={wbef=278}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有278秒"}]}
execute positioned as @s[scores={wbef=277}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有277秒"}]}
execute positioned as @s[scores={wbef=276}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有276秒"}]}
execute positioned as @s[scores={wbef=275}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有275秒"}]}
execute positioned as @s[scores={wbef=274}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有274秒"}]}
execute positioned as @s[scores={wbef=273}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有273秒"}]}
execute positioned as @s[scores={wbef=272}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有272秒"}]}
execute positioned as @s[scores={wbef=271}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有271秒"}]}
execute positioned as @s[scores={wbef=270}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有270秒"}]}
execute positioned as @s[scores={wbef=269}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有269秒"}]}
execute positioned as @s[scores={wbef=268}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有268秒"}]}
execute positioned as @s[scores={wbef=267}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有267秒"}]}
execute positioned as @s[scores={wbef=266}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有266秒"}]}
execute positioned as @s[scores={wbef=265}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有265秒"}]}
execute positioned as @s[scores={wbef=264}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有264秒"}]}
execute positioned as @s[scores={wbef=263}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有263秒"}]}
execute positioned as @s[scores={wbef=262}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有262秒"}]}
execute positioned as @s[scores={wbef=261}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有261秒"}]}
execute positioned as @s[scores={wbef=260}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有260秒"}]}
execute positioned as @s[scores={wbef=259}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有259秒"}]}
execute positioned as @s[scores={wbef=258}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有258秒"}]}
execute positioned as @s[scores={wbef=257}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有257秒"}]}
execute positioned as @s[scores={wbef=256}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有256秒"}]}
execute positioned as @s[scores={wbef=255}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有255秒"}]}
execute positioned as @s[scores={wbef=254}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有254秒"}]}
execute positioned as @s[scores={wbef=253}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有253秒"}]}
execute positioned as @s[scores={wbef=252}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有252秒"}]}
execute positioned as @s[scores={wbef=251}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有251秒"}]}
execute positioned as @s[scores={wbef=250}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有250秒"}]}
execute positioned as @s[scores={wbef=249}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有249秒"}]}
execute positioned as @s[scores={wbef=248}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有248秒"}]}
execute positioned as @s[scores={wbef=247}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有247秒"}]}
execute positioned as @s[scores={wbef=246}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有246秒"}]}
execute positioned as @s[scores={wbef=245}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有245秒"}]}
execute positioned as @s[scores={wbef=244}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有244秒"}]}
execute positioned as @s[scores={wbef=243}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有243秒"}]}
execute positioned as @s[scores={wbef=242}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有242秒"}]}
execute positioned as @s[scores={wbef=241}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有241秒"}]}
execute positioned as @s[scores={wbef=240}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有240秒"}]}
execute positioned as @s[scores={wbef=239}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有239秒"}]}
execute positioned as @s[scores={wbef=238}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有238秒"}]}
execute positioned as @s[scores={wbef=237}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有237秒"}]}
execute positioned as @s[scores={wbef=236}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有236秒"}]}
execute positioned as @s[scores={wbef=235}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有235秒"}]}
execute positioned as @s[scores={wbef=234}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有234秒"}]}
execute positioned as @s[scores={wbef=233}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有233秒"}]}
execute positioned as @s[scores={wbef=232}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有232秒"}]}
execute positioned as @s[scores={wbef=231}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有231秒"}]}
execute positioned as @s[scores={wbef=230}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有230秒"}]}
execute positioned as @s[scores={wbef=229}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有229秒"}]}
execute positioned as @s[scores={wbef=228}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有228秒"}]}
execute positioned as @s[scores={wbef=227}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有227秒"}]}
execute positioned as @s[scores={wbef=226}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有226秒"}]}
execute positioned as @s[scores={wbef=225}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有225秒"}]}
execute positioned as @s[scores={wbef=224}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有224秒"}]}
execute positioned as @s[scores={wbef=223}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有223秒"}]}
execute positioned as @s[scores={wbef=222}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有222秒"}]}
execute positioned as @s[scores={wbef=221}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有221秒"}]}
execute positioned as @s[scores={wbef=220}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有220秒"}]}
execute positioned as @s[scores={wbef=219}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有219秒"}]}
execute positioned as @s[scores={wbef=218}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有218秒"}]}
execute positioned as @s[scores={wbef=217}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有217秒"}]}
execute positioned as @s[scores={wbef=216}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有216秒"}]}
execute positioned as @s[scores={wbef=215}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有215秒"}]}
execute positioned as @s[scores={wbef=214}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有214秒"}]}
execute positioned as @s[scores={wbef=213}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有213秒"}]}
execute positioned as @s[scores={wbef=212}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有212秒"}]}
execute positioned as @s[scores={wbef=211}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有211秒"}]}
execute positioned as @s[scores={wbef=210}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有210秒"}]}
execute positioned as @s[scores={wbef=209}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有209秒"}]}
execute positioned as @s[scores={wbef=208}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有208秒"}]}
execute positioned as @s[scores={wbef=207}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有207秒"}]}
execute positioned as @s[scores={wbef=206}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有206秒"}]}
execute positioned as @s[scores={wbef=205}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有205秒"}]}
execute positioned as @s[scores={wbef=204}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有204秒"}]}
execute positioned as @s[scores={wbef=203}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有203秒"}]}
execute positioned as @s[scores={wbef=202}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有202秒"}]}
execute positioned as @s[scores={wbef=201}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有201秒"}]}
execute positioned as @s[scores={wbef=200}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有200秒"}]}
execute positioned as @s[scores={wbef=199}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有199秒"}]}
execute positioned as @s[scores={wbef=198}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有198秒"}]}
execute positioned as @s[scores={wbef=197}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有197秒"}]}
execute positioned as @s[scores={wbef=196}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有196秒"}]}
execute positioned as @s[scores={wbef=195}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有195秒"}]}
execute positioned as @s[scores={wbef=194}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有194秒"}]}
execute positioned as @s[scores={wbef=193}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有193秒"}]}
execute positioned as @s[scores={wbef=192}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有192秒"}]}
execute positioned as @s[scores={wbef=191}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有191秒"}]}
execute positioned as @s[scores={wbef=190}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有190秒"}]}
execute positioned as @s[scores={wbef=189}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有189秒"}]}
execute positioned as @s[scores={wbef=188}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有188秒"}]}
execute positioned as @s[scores={wbef=187}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有187秒"}]}
execute positioned as @s[scores={wbef=186}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有186秒"}]}
execute positioned as @s[scores={wbef=185}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有185秒"}]}
execute positioned as @s[scores={wbef=184}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有184秒"}]}
execute positioned as @s[scores={wbef=183}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有183秒"}]}
execute positioned as @s[scores={wbef=182}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有182秒"}]}
execute positioned as @s[scores={wbef=181}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有181秒"}]}
execute positioned as @s[scores={wbef=180}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有180秒"}]}
execute positioned as @s[scores={wbef=179}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有179秒"}]}
execute positioned as @s[scores={wbef=178}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有178秒"}]}
execute positioned as @s[scores={wbef=177}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有177秒"}]}
execute positioned as @s[scores={wbef=176}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有176秒"}]}
execute positioned as @s[scores={wbef=175}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有175秒"}]}
execute positioned as @s[scores={wbef=174}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有174秒"}]}
execute positioned as @s[scores={wbef=173}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有173秒"}]}
execute positioned as @s[scores={wbef=172}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有172秒"}]}
execute positioned as @s[scores={wbef=171}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有171秒"}]}
execute positioned as @s[scores={wbef=170}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有170秒"}]}
execute positioned as @s[scores={wbef=169}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有169秒"}]}
execute positioned as @s[scores={wbef=168}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有168秒"}]}
execute positioned as @s[scores={wbef=167}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有167秒"}]}
execute positioned as @s[scores={wbef=166}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有166秒"}]}
execute positioned as @s[scores={wbef=165}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有165秒"}]}
execute positioned as @s[scores={wbef=164}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有164秒"}]}
execute positioned as @s[scores={wbef=163}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有163秒"}]}
execute positioned as @s[scores={wbef=162}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有162秒"}]}
execute positioned as @s[scores={wbef=161}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有161秒"}]}
execute positioned as @s[scores={wbef=160}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有160秒"}]}
execute positioned as @s[scores={wbef=159}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有159秒"}]}
execute positioned as @s[scores={wbef=158}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有158秒"}]}
execute positioned as @s[scores={wbef=157}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有157秒"}]}
execute positioned as @s[scores={wbef=156}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有156秒"}]}
execute positioned as @s[scores={wbef=155}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有155秒"}]}
execute positioned as @s[scores={wbef=154}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有154秒"}]}
execute positioned as @s[scores={wbef=153}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有153秒"}]}
execute positioned as @s[scores={wbef=152}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有152秒"}]}
execute positioned as @s[scores={wbef=151}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有151秒"}]}
execute positioned as @s[scores={wbef=150}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有150秒"}]}
execute positioned as @s[scores={wbef=149}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有149秒"}]}
execute positioned as @s[scores={wbef=148}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有148秒"}]}
execute positioned as @s[scores={wbef=147}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有147秒"}]}
execute positioned as @s[scores={wbef=146}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有146秒"}]}
execute positioned as @s[scores={wbef=145}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有145秒"}]}
execute positioned as @s[scores={wbef=144}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有144秒"}]}
execute positioned as @s[scores={wbef=143}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有143秒"}]}
execute positioned as @s[scores={wbef=142}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有142秒"}]}
execute positioned as @s[scores={wbef=141}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有141秒"}]}
execute positioned as @s[scores={wbef=140}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有140秒"}]}
execute positioned as @s[scores={wbef=139}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有139秒"}]}
execute positioned as @s[scores={wbef=138}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有138秒"}]}
execute positioned as @s[scores={wbef=137}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有137秒"}]}
execute positioned as @s[scores={wbef=136}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有136秒"}]}
execute positioned as @s[scores={wbef=135}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有135秒"}]}
execute positioned as @s[scores={wbef=134}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有134秒"}]}
execute positioned as @s[scores={wbef=133}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有133秒"}]}
execute positioned as @s[scores={wbef=132}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有132秒"}]}
execute positioned as @s[scores={wbef=131}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有131秒"}]}
execute positioned as @s[scores={wbef=130}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有130秒"}]}
execute positioned as @s[scores={wbef=129}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有129秒"}]}
execute positioned as @s[scores={wbef=128}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有128秒"}]}
execute positioned as @s[scores={wbef=127}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有127秒"}]}
execute positioned as @s[scores={wbef=126}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有126秒"}]}
execute positioned as @s[scores={wbef=125}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有125秒"}]}
execute positioned as @s[scores={wbef=124}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有124秒"}]}
execute positioned as @s[scores={wbef=123}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有123秒"}]}
execute positioned as @s[scores={wbef=122}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有122秒"}]}
execute positioned as @s[scores={wbef=121}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有121秒"}]}
execute positioned as @s[scores={wbef=120}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有120秒"}]}
execute positioned as @s[scores={wbef=119}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有119秒"}]}
execute positioned as @s[scores={wbef=118}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有118秒"}]}
execute positioned as @s[scores={wbef=117}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有117秒"}]}
execute positioned as @s[scores={wbef=116}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有116秒"}]}
execute positioned as @s[scores={wbef=115}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有115秒"}]}
execute positioned as @s[scores={wbef=114}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有114秒"}]}
execute positioned as @s[scores={wbef=113}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有113秒"}]}
execute positioned as @s[scores={wbef=112}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有112秒"}]}
execute positioned as @s[scores={wbef=111}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有111秒"}]}
execute positioned as @s[scores={wbef=110}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有110秒"}]}
execute positioned as @s[scores={wbef=109}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有109秒"}]}
execute positioned as @s[scores={wbef=108}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有108秒"}]}
execute positioned as @s[scores={wbef=107}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有107秒"}]}
execute positioned as @s[scores={wbef=106}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有106秒"}]}
execute positioned as @s[scores={wbef=105}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有105秒"}]}
execute positioned as @s[scores={wbef=104}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有104秒"}]}
execute positioned as @s[scores={wbef=103}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有103秒"}]}
execute positioned as @s[scores={wbef=102}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有102秒"}]}
execute positioned as @s[scores={wbef=101}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有101秒"}]}
execute positioned as @s[scores={wbef=100}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有100秒"}]}
execute positioned as @s[scores={wbef=99}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有99秒"}]}
execute positioned as @s[scores={wbef=98}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有98秒"}]}
execute positioned as @s[scores={wbef=97}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有97秒"}]}
execute positioned as @s[scores={wbef=96}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有96秒"}]}
execute positioned as @s[scores={wbef=95}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有95秒"}]}
execute positioned as @s[scores={wbef=94}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有94秒"}]}
execute positioned as @s[scores={wbef=93}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有93秒"}]}
execute positioned as @s[scores={wbef=92}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有92秒"}]}
execute positioned as @s[scores={wbef=91}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有91秒"}]}
execute positioned as @s[scores={wbef=90}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有90秒"}]}
execute positioned as @s[scores={wbef=89}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有89秒"}]}
execute positioned as @s[scores={wbef=88}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有88秒"}]}
execute positioned as @s[scores={wbef=87}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有87秒"}]}
execute positioned as @s[scores={wbef=86}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有86秒"}]}
execute positioned as @s[scores={wbef=85}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有85秒"}]}
execute positioned as @s[scores={wbef=84}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有84秒"}]}
execute positioned as @s[scores={wbef=83}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有83秒"}]}
execute positioned as @s[scores={wbef=82}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有82秒"}]}
execute positioned as @s[scores={wbef=81}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有81秒"}]}
execute positioned as @s[scores={wbef=80}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有80秒"}]}
execute positioned as @s[scores={wbef=79}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有79秒"}]}
execute positioned as @s[scores={wbef=78}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有78秒"}]}
execute positioned as @s[scores={wbef=77}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有77秒"}]}
execute positioned as @s[scores={wbef=76}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有76秒"}]}
execute positioned as @s[scores={wbef=75}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有75秒"}]}
execute positioned as @s[scores={wbef=74}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有74秒"}]}
execute positioned as @s[scores={wbef=73}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有73秒"}]}
execute positioned as @s[scores={wbef=72}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有72秒"}]}
execute positioned as @s[scores={wbef=71}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有71秒"}]}
execute positioned as @s[scores={wbef=70}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有70秒"}]}
execute positioned as @s[scores={wbef=69}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有69秒"}]}
execute positioned as @s[scores={wbef=68}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有68秒"}]}
execute positioned as @s[scores={wbef=67}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有67秒"}]}
execute positioned as @s[scores={wbef=66}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有66秒"}]}
execute positioned as @s[scores={wbef=65}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有65秒"}]}
execute positioned as @s[scores={wbef=64}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有64秒"}]}
execute positioned as @s[scores={wbef=63}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有63秒"}]}
execute positioned as @s[scores={wbef=62}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有62秒"}]}
execute positioned as @s[scores={wbef=61}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有61秒"}]}
execute positioned as @s[scores={wbef=60}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有60秒"}]}
execute positioned as @s[scores={wbef=59}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有59秒"}]}
execute positioned as @s[scores={wbef=58}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有58秒"}]}
execute positioned as @s[scores={wbef=57}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有57秒"}]}
execute positioned as @s[scores={wbef=56}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有56秒"}]}
execute positioned as @s[scores={wbef=55}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有55秒"}]}
execute positioned as @s[scores={wbef=54}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有54秒"}]}
execute positioned as @s[scores={wbef=53}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有53秒"}]}
execute positioned as @s[scores={wbef=52}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有52秒"}]}
execute positioned as @s[scores={wbef=51}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有51秒"}]}
execute positioned as @s[scores={wbef=50}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有50秒"}]}
execute positioned as @s[scores={wbef=49}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有49秒"}]}
execute positioned as @s[scores={wbef=48}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有48秒"}]}
execute positioned as @s[scores={wbef=47}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有47秒"}]}
execute positioned as @s[scores={wbef=46}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有46秒"}]}
execute positioned as @s[scores={wbef=45}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有45秒"}]}
execute positioned as @s[scores={wbef=44}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有44秒"}]}
execute positioned as @s[scores={wbef=43}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有43秒"}]}
execute positioned as @s[scores={wbef=42}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有42秒"}]}
execute positioned as @s[scores={wbef=41}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有41秒"}]}
execute positioned as @s[scores={wbef=40}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有40秒"}]}
execute positioned as @s[scores={wbef=39}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有39秒"}]}
execute positioned as @s[scores={wbef=38}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有38秒"}]}
execute positioned as @s[scores={wbef=37}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有37秒"}]}
execute positioned as @s[scores={wbef=36}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有36秒"}]}
execute positioned as @s[scores={wbef=35}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有35秒"}]}
execute positioned as @s[scores={wbef=34}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有34秒"}]}
execute positioned as @s[scores={wbef=33}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有33秒"}]}
execute positioned as @s[scores={wbef=32}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有32秒"}]}
execute positioned as @s[scores={wbef=31}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有31秒"}]}
execute positioned as @s[scores={wbef=30}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有30秒"}]}
execute positioned as @s[scores={wbef=29}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有29秒"}]}
execute positioned as @s[scores={wbef=28}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有28秒"}]}
execute positioned as @s[scores={wbef=27}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有27秒"}]}
execute positioned as @s[scores={wbef=26}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有26秒"}]}
execute positioned as @s[scores={wbef=25}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有25秒"}]}
execute positioned as @s[scores={wbef=24}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有24秒"}]}
execute positioned as @s[scores={wbef=23}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有23秒"}]}
execute positioned as @s[scores={wbef=22}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有22秒"}]}
execute positioned as @s[scores={wbef=21}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有21秒"}]}
execute positioned as @s[scores={wbef=20}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有20秒"}]}
execute positioned as @s[scores={wbef=19}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有19秒"}]}
execute positioned as @s[scores={wbef=18}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有18秒"}]}
execute positioned as @s[scores={wbef=17}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有17秒"}]}
execute positioned as @s[scores={wbef=16}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有16秒"}]}
execute positioned as @s[scores={wbef=15}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有15秒"}]}
execute positioned as @s[scores={wbef=14}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有14秒"}]}
execute positioned as @s[scores={wbef=13}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有13秒"}]}
execute positioned as @s[scores={wbef=12}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有12秒"}]}
execute positioned as @s[scores={wbef=11}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有11秒"}]}
execute positioned as @s[scores={wbef=10}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有10秒"}]}
execute positioned as @s[scores={wbef=9}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有9秒"}]}
execute positioned as @s[scores={wbef=8}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有8秒"}]}
execute positioned as @s[scores={wbef=7}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有7秒"}]}
execute positioned as @s[scores={wbef=6}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有6秒"}]}
execute positioned as @s[scores={wbef=5}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有5秒"}]}
execute positioned as @s[scores={wbef=4}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有4秒"}]}
execute positioned as @s[scores={wbef=3}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有3秒"}]}
execute positioned as @s[scores={wbef=2}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有2秒"}]}
execute positioned as @s[scores={wbef=1}] run tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有1秒"}]}