tag @s[scores={wbef=-100..}] add wbefz
execute @s[tag=!wbefz] ~ ~ ~ scoreboard players set @s wbef 0
tag @s remove wbefz
execute @s[scores={wbef=0}] ~ ~ ~ function grade/effect2
execute @s[scores={wbef=0}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力触发成功！"}]}
execute @s[scores={wbef=0}] ~ ~ ~ scoreboard players add @s wbef 600
execute @s[scores={wbef=600}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有600秒"}]}
execute @s[scores={wbef=599}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有599秒"}]}
execute @s[scores={wbef=598}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有598秒"}]}
execute @s[scores={wbef=597}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有597秒"}]}
execute @s[scores={wbef=596}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有596秒"}]}
execute @s[scores={wbef=595}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有595秒"}]}
execute @s[scores={wbef=594}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有594秒"}]}
execute @s[scores={wbef=593}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有593秒"}]}
execute @s[scores={wbef=592}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有592秒"}]}
execute @s[scores={wbef=591}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有591秒"}]}
execute @s[scores={wbef=590}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有590秒"}]}
execute @s[scores={wbef=589}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有589秒"}]}
execute @s[scores={wbef=588}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有588秒"}]}
execute @s[scores={wbef=587}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有587秒"}]}
execute @s[scores={wbef=586}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有586秒"}]}
execute @s[scores={wbef=585}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有585秒"}]}
execute @s[scores={wbef=584}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有584秒"}]}
execute @s[scores={wbef=583}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有583秒"}]}
execute @s[scores={wbef=582}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有582秒"}]}
execute @s[scores={wbef=581}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有581秒"}]}
execute @s[scores={wbef=580}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有580秒"}]}
execute @s[scores={wbef=579}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有579秒"}]}
execute @s[scores={wbef=578}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有578秒"}]}
execute @s[scores={wbef=577}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有577秒"}]}
execute @s[scores={wbef=576}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有576秒"}]}
execute @s[scores={wbef=575}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有575秒"}]}
execute @s[scores={wbef=574}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有574秒"}]}
execute @s[scores={wbef=573}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有573秒"}]}
execute @s[scores={wbef=572}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有572秒"}]}
execute @s[scores={wbef=571}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有571秒"}]}
execute @s[scores={wbef=570}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有570秒"}]}
execute @s[scores={wbef=569}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有569秒"}]}
execute @s[scores={wbef=568}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有568秒"}]}
execute @s[scores={wbef=567}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有567秒"}]}
execute @s[scores={wbef=566}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有566秒"}]}
execute @s[scores={wbef=565}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有565秒"}]}
execute @s[scores={wbef=564}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有564秒"}]}
execute @s[scores={wbef=563}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有563秒"}]}
execute @s[scores={wbef=562}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有562秒"}]}
execute @s[scores={wbef=561}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有561秒"}]}
execute @s[scores={wbef=560}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有560秒"}]}
execute @s[scores={wbef=559}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有559秒"}]}
execute @s[scores={wbef=558}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有558秒"}]}
execute @s[scores={wbef=557}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有557秒"}]}
execute @s[scores={wbef=556}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有556秒"}]}
execute @s[scores={wbef=555}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有555秒"}]}
execute @s[scores={wbef=554}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有554秒"}]}
execute @s[scores={wbef=553}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有553秒"}]}
execute @s[scores={wbef=552}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有552秒"}]}
execute @s[scores={wbef=551}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有551秒"}]}
execute @s[scores={wbef=550}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有550秒"}]}
execute @s[scores={wbef=549}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有549秒"}]}
execute @s[scores={wbef=548}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有548秒"}]}
execute @s[scores={wbef=547}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有547秒"}]}
execute @s[scores={wbef=546}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有546秒"}]}
execute @s[scores={wbef=545}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有545秒"}]}
execute @s[scores={wbef=544}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有544秒"}]}
execute @s[scores={wbef=543}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有543秒"}]}
execute @s[scores={wbef=542}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有542秒"}]}
execute @s[scores={wbef=541}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有541秒"}]}
execute @s[scores={wbef=540}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有540秒"}]}
execute @s[scores={wbef=539}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有539秒"}]}
execute @s[scores={wbef=538}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有538秒"}]}
execute @s[scores={wbef=537}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有537秒"}]}
execute @s[scores={wbef=536}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有536秒"}]}
execute @s[scores={wbef=535}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有535秒"}]}
execute @s[scores={wbef=534}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有534秒"}]}
execute @s[scores={wbef=533}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有533秒"}]}
execute @s[scores={wbef=532}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有532秒"}]}
execute @s[scores={wbef=531}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有531秒"}]}
execute @s[scores={wbef=530}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有530秒"}]}
execute @s[scores={wbef=529}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有529秒"}]}
execute @s[scores={wbef=528}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有528秒"}]}
execute @s[scores={wbef=527}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有527秒"}]}
execute @s[scores={wbef=526}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有526秒"}]}
execute @s[scores={wbef=525}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有525秒"}]}
execute @s[scores={wbef=524}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有524秒"}]}
execute @s[scores={wbef=523}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有523秒"}]}
execute @s[scores={wbef=522}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有522秒"}]}
execute @s[scores={wbef=521}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有521秒"}]}
execute @s[scores={wbef=520}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有520秒"}]}
execute @s[scores={wbef=519}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有519秒"}]}
execute @s[scores={wbef=518}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有518秒"}]}
execute @s[scores={wbef=517}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有517秒"}]}
execute @s[scores={wbef=516}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有516秒"}]}
execute @s[scores={wbef=515}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有515秒"}]}
execute @s[scores={wbef=514}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有514秒"}]}
execute @s[scores={wbef=513}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有513秒"}]}
execute @s[scores={wbef=512}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有512秒"}]}
execute @s[scores={wbef=511}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有511秒"}]}
execute @s[scores={wbef=510}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有510秒"}]}
execute @s[scores={wbef=509}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有509秒"}]}
execute @s[scores={wbef=508}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有508秒"}]}
execute @s[scores={wbef=507}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有507秒"}]}
execute @s[scores={wbef=506}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有506秒"}]}
execute @s[scores={wbef=505}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有505秒"}]}
execute @s[scores={wbef=504}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有504秒"}]}
execute @s[scores={wbef=503}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有503秒"}]}
execute @s[scores={wbef=502}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有502秒"}]}
execute @s[scores={wbef=501}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有501秒"}]}
execute @s[scores={wbef=500}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有500秒"}]}
execute @s[scores={wbef=499}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有499秒"}]}
execute @s[scores={wbef=498}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有498秒"}]}
execute @s[scores={wbef=497}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有497秒"}]}
execute @s[scores={wbef=496}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有496秒"}]}
execute @s[scores={wbef=495}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有495秒"}]}
execute @s[scores={wbef=494}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有494秒"}]}
execute @s[scores={wbef=493}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有493秒"}]}
execute @s[scores={wbef=492}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有492秒"}]}
execute @s[scores={wbef=491}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有491秒"}]}
execute @s[scores={wbef=490}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有490秒"}]}
execute @s[scores={wbef=489}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有489秒"}]}
execute @s[scores={wbef=488}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有488秒"}]}
execute @s[scores={wbef=487}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有487秒"}]}
execute @s[scores={wbef=486}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有486秒"}]}
execute @s[scores={wbef=485}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有485秒"}]}
execute @s[scores={wbef=484}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有484秒"}]}
execute @s[scores={wbef=483}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有483秒"}]}
execute @s[scores={wbef=482}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有482秒"}]}
execute @s[scores={wbef=481}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有481秒"}]}
execute @s[scores={wbef=480}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有480秒"}]}
execute @s[scores={wbef=479}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有479秒"}]}
execute @s[scores={wbef=478}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有478秒"}]}
execute @s[scores={wbef=477}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有477秒"}]}
execute @s[scores={wbef=476}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有476秒"}]}
execute @s[scores={wbef=475}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有475秒"}]}
execute @s[scores={wbef=474}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有474秒"}]}
execute @s[scores={wbef=473}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有473秒"}]}
execute @s[scores={wbef=472}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有472秒"}]}
execute @s[scores={wbef=471}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有471秒"}]}
execute @s[scores={wbef=470}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有470秒"}]}
execute @s[scores={wbef=469}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有469秒"}]}
execute @s[scores={wbef=468}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有468秒"}]}
execute @s[scores={wbef=467}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有467秒"}]}
execute @s[scores={wbef=466}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有466秒"}]}
execute @s[scores={wbef=465}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有465秒"}]}
execute @s[scores={wbef=464}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有464秒"}]}
execute @s[scores={wbef=463}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有463秒"}]}
execute @s[scores={wbef=462}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有462秒"}]}
execute @s[scores={wbef=461}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有461秒"}]}
execute @s[scores={wbef=460}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有460秒"}]}
execute @s[scores={wbef=459}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有459秒"}]}
execute @s[scores={wbef=458}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有458秒"}]}
execute @s[scores={wbef=457}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有457秒"}]}
execute @s[scores={wbef=456}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有456秒"}]}
execute @s[scores={wbef=455}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有455秒"}]}
execute @s[scores={wbef=454}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有454秒"}]}
execute @s[scores={wbef=453}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有453秒"}]}
execute @s[scores={wbef=452}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有452秒"}]}
execute @s[scores={wbef=451}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有451秒"}]}
execute @s[scores={wbef=450}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有450秒"}]}
execute @s[scores={wbef=449}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有449秒"}]}
execute @s[scores={wbef=448}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有448秒"}]}
execute @s[scores={wbef=447}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有447秒"}]}
execute @s[scores={wbef=446}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有446秒"}]}
execute @s[scores={wbef=445}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有445秒"}]}
execute @s[scores={wbef=444}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有444秒"}]}
execute @s[scores={wbef=443}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有443秒"}]}
execute @s[scores={wbef=442}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有442秒"}]}
execute @s[scores={wbef=441}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有441秒"}]}
execute @s[scores={wbef=440}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有440秒"}]}
execute @s[scores={wbef=439}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有439秒"}]}
execute @s[scores={wbef=438}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有438秒"}]}
execute @s[scores={wbef=437}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有437秒"}]}
execute @s[scores={wbef=436}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有436秒"}]}
execute @s[scores={wbef=435}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有435秒"}]}
execute @s[scores={wbef=434}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有434秒"}]}
execute @s[scores={wbef=433}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有433秒"}]}
execute @s[scores={wbef=432}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有432秒"}]}
execute @s[scores={wbef=431}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有431秒"}]}
execute @s[scores={wbef=430}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有430秒"}]}
execute @s[scores={wbef=429}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有429秒"}]}
execute @s[scores={wbef=428}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有428秒"}]}
execute @s[scores={wbef=427}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有427秒"}]}
execute @s[scores={wbef=426}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有426秒"}]}
execute @s[scores={wbef=425}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有425秒"}]}
execute @s[scores={wbef=424}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有424秒"}]}
execute @s[scores={wbef=423}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有423秒"}]}
execute @s[scores={wbef=422}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有422秒"}]}
execute @s[scores={wbef=421}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有421秒"}]}
execute @s[scores={wbef=420}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有420秒"}]}
execute @s[scores={wbef=419}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有419秒"}]}
execute @s[scores={wbef=418}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有418秒"}]}
execute @s[scores={wbef=417}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有417秒"}]}
execute @s[scores={wbef=416}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有416秒"}]}
execute @s[scores={wbef=415}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有415秒"}]}
execute @s[scores={wbef=414}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有414秒"}]}
execute @s[scores={wbef=413}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有413秒"}]}
execute @s[scores={wbef=412}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有412秒"}]}
execute @s[scores={wbef=411}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有411秒"}]}
execute @s[scores={wbef=410}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有410秒"}]}
execute @s[scores={wbef=409}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有409秒"}]}
execute @s[scores={wbef=408}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有408秒"}]}
execute @s[scores={wbef=407}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有407秒"}]}
execute @s[scores={wbef=406}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有406秒"}]}
execute @s[scores={wbef=405}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有405秒"}]}
execute @s[scores={wbef=404}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有404秒"}]}
execute @s[scores={wbef=403}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有403秒"}]}
execute @s[scores={wbef=402}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有402秒"}]}
execute @s[scores={wbef=401}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有401秒"}]}
execute @s[scores={wbef=400}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有400秒"}]}
execute @s[scores={wbef=399}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有399秒"}]}
execute @s[scores={wbef=398}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有398秒"}]}
execute @s[scores={wbef=397}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有397秒"}]}
execute @s[scores={wbef=396}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有396秒"}]}
execute @s[scores={wbef=395}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有395秒"}]}
execute @s[scores={wbef=394}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有394秒"}]}
execute @s[scores={wbef=393}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有393秒"}]}
execute @s[scores={wbef=392}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有392秒"}]}
execute @s[scores={wbef=391}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有391秒"}]}
execute @s[scores={wbef=390}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有390秒"}]}
execute @s[scores={wbef=389}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有389秒"}]}
execute @s[scores={wbef=388}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有388秒"}]}
execute @s[scores={wbef=387}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有387秒"}]}
execute @s[scores={wbef=386}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有386秒"}]}
execute @s[scores={wbef=385}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有385秒"}]}
execute @s[scores={wbef=384}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有384秒"}]}
execute @s[scores={wbef=383}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有383秒"}]}
execute @s[scores={wbef=382}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有382秒"}]}
execute @s[scores={wbef=381}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有381秒"}]}
execute @s[scores={wbef=380}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有380秒"}]}
execute @s[scores={wbef=379}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有379秒"}]}
execute @s[scores={wbef=378}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有378秒"}]}
execute @s[scores={wbef=377}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有377秒"}]}
execute @s[scores={wbef=376}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有376秒"}]}
execute @s[scores={wbef=375}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有375秒"}]}
execute @s[scores={wbef=374}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有374秒"}]}
execute @s[scores={wbef=373}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有373秒"}]}
execute @s[scores={wbef=372}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有372秒"}]}
execute @s[scores={wbef=371}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有371秒"}]}
execute @s[scores={wbef=370}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有370秒"}]}
execute @s[scores={wbef=369}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有369秒"}]}
execute @s[scores={wbef=368}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有368秒"}]}
execute @s[scores={wbef=367}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有367秒"}]}
execute @s[scores={wbef=366}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有366秒"}]}
execute @s[scores={wbef=365}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有365秒"}]}
execute @s[scores={wbef=364}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有364秒"}]}
execute @s[scores={wbef=363}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有363秒"}]}
execute @s[scores={wbef=362}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有362秒"}]}
execute @s[scores={wbef=361}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有361秒"}]}
execute @s[scores={wbef=360}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有360秒"}]}
execute @s[scores={wbef=359}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有359秒"}]}
execute @s[scores={wbef=358}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有358秒"}]}
execute @s[scores={wbef=357}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有357秒"}]}
execute @s[scores={wbef=356}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有356秒"}]}
execute @s[scores={wbef=355}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有355秒"}]}
execute @s[scores={wbef=354}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有354秒"}]}
execute @s[scores={wbef=353}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有353秒"}]}
execute @s[scores={wbef=352}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有352秒"}]}
execute @s[scores={wbef=351}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有351秒"}]}
execute @s[scores={wbef=350}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有350秒"}]}
execute @s[scores={wbef=349}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有349秒"}]}
execute @s[scores={wbef=348}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有348秒"}]}
execute @s[scores={wbef=347}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有347秒"}]}
execute @s[scores={wbef=346}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有346秒"}]}
execute @s[scores={wbef=345}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有345秒"}]}
execute @s[scores={wbef=344}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有344秒"}]}
execute @s[scores={wbef=343}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有343秒"}]}
execute @s[scores={wbef=342}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有342秒"}]}
execute @s[scores={wbef=341}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有341秒"}]}
execute @s[scores={wbef=340}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有340秒"}]}
execute @s[scores={wbef=339}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有339秒"}]}
execute @s[scores={wbef=338}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有338秒"}]}
execute @s[scores={wbef=337}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有337秒"}]}
execute @s[scores={wbef=336}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有336秒"}]}
execute @s[scores={wbef=335}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有335秒"}]}
execute @s[scores={wbef=334}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有334秒"}]}
execute @s[scores={wbef=333}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有333秒"}]}
execute @s[scores={wbef=332}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有332秒"}]}
execute @s[scores={wbef=331}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有331秒"}]}
execute @s[scores={wbef=330}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有330秒"}]}
execute @s[scores={wbef=329}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有329秒"}]}
execute @s[scores={wbef=328}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有328秒"}]}
execute @s[scores={wbef=327}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有327秒"}]}
execute @s[scores={wbef=326}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有326秒"}]}
execute @s[scores={wbef=325}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有325秒"}]}
execute @s[scores={wbef=324}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有324秒"}]}
execute @s[scores={wbef=323}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有323秒"}]}
execute @s[scores={wbef=322}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有322秒"}]}
execute @s[scores={wbef=321}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有321秒"}]}
execute @s[scores={wbef=320}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有320秒"}]}
execute @s[scores={wbef=319}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有319秒"}]}
execute @s[scores={wbef=318}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有318秒"}]}
execute @s[scores={wbef=317}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有317秒"}]}
execute @s[scores={wbef=316}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有316秒"}]}
execute @s[scores={wbef=315}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有315秒"}]}
execute @s[scores={wbef=314}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有314秒"}]}
execute @s[scores={wbef=313}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有313秒"}]}
execute @s[scores={wbef=312}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有312秒"}]}
execute @s[scores={wbef=311}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有311秒"}]}
execute @s[scores={wbef=310}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有310秒"}]}
execute @s[scores={wbef=309}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有309秒"}]}
execute @s[scores={wbef=308}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有308秒"}]}
execute @s[scores={wbef=307}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有307秒"}]}
execute @s[scores={wbef=306}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有306秒"}]}
execute @s[scores={wbef=305}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有305秒"}]}
execute @s[scores={wbef=304}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有304秒"}]}
execute @s[scores={wbef=303}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有303秒"}]}
execute @s[scores={wbef=302}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有302秒"}]}
execute @s[scores={wbef=301}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有301秒"}]}
execute @s[scores={wbef=300}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有300秒"}]}
execute @s[scores={wbef=299}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有299秒"}]}
execute @s[scores={wbef=298}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有298秒"}]}
execute @s[scores={wbef=297}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有297秒"}]}
execute @s[scores={wbef=296}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有296秒"}]}
execute @s[scores={wbef=295}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有295秒"}]}
execute @s[scores={wbef=294}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有294秒"}]}
execute @s[scores={wbef=293}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有293秒"}]}
execute @s[scores={wbef=292}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有292秒"}]}
execute @s[scores={wbef=291}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有291秒"}]}
execute @s[scores={wbef=290}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有290秒"}]}
execute @s[scores={wbef=289}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有289秒"}]}
execute @s[scores={wbef=288}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有288秒"}]}
execute @s[scores={wbef=287}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有287秒"}]}
execute @s[scores={wbef=286}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有286秒"}]}
execute @s[scores={wbef=285}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有285秒"}]}
execute @s[scores={wbef=284}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有284秒"}]}
execute @s[scores={wbef=283}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有283秒"}]}
execute @s[scores={wbef=282}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有282秒"}]}
execute @s[scores={wbef=281}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有281秒"}]}
execute @s[scores={wbef=280}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有280秒"}]}
execute @s[scores={wbef=279}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有279秒"}]}
execute @s[scores={wbef=278}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有278秒"}]}
execute @s[scores={wbef=277}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有277秒"}]}
execute @s[scores={wbef=276}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有276秒"}]}
execute @s[scores={wbef=275}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有275秒"}]}
execute @s[scores={wbef=274}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有274秒"}]}
execute @s[scores={wbef=273}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有273秒"}]}
execute @s[scores={wbef=272}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有272秒"}]}
execute @s[scores={wbef=271}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有271秒"}]}
execute @s[scores={wbef=270}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有270秒"}]}
execute @s[scores={wbef=269}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有269秒"}]}
execute @s[scores={wbef=268}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有268秒"}]}
execute @s[scores={wbef=267}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有267秒"}]}
execute @s[scores={wbef=266}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有266秒"}]}
execute @s[scores={wbef=265}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有265秒"}]}
execute @s[scores={wbef=264}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有264秒"}]}
execute @s[scores={wbef=263}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有263秒"}]}
execute @s[scores={wbef=262}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有262秒"}]}
execute @s[scores={wbef=261}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有261秒"}]}
execute @s[scores={wbef=260}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有260秒"}]}
execute @s[scores={wbef=259}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有259秒"}]}
execute @s[scores={wbef=258}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有258秒"}]}
execute @s[scores={wbef=257}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有257秒"}]}
execute @s[scores={wbef=256}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有256秒"}]}
execute @s[scores={wbef=255}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有255秒"}]}
execute @s[scores={wbef=254}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有254秒"}]}
execute @s[scores={wbef=253}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有253秒"}]}
execute @s[scores={wbef=252}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有252秒"}]}
execute @s[scores={wbef=251}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有251秒"}]}
execute @s[scores={wbef=250}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有250秒"}]}
execute @s[scores={wbef=249}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有249秒"}]}
execute @s[scores={wbef=248}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有248秒"}]}
execute @s[scores={wbef=247}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有247秒"}]}
execute @s[scores={wbef=246}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有246秒"}]}
execute @s[scores={wbef=245}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有245秒"}]}
execute @s[scores={wbef=244}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有244秒"}]}
execute @s[scores={wbef=243}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有243秒"}]}
execute @s[scores={wbef=242}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有242秒"}]}
execute @s[scores={wbef=241}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有241秒"}]}
execute @s[scores={wbef=240}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有240秒"}]}
execute @s[scores={wbef=239}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有239秒"}]}
execute @s[scores={wbef=238}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有238秒"}]}
execute @s[scores={wbef=237}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有237秒"}]}
execute @s[scores={wbef=236}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有236秒"}]}
execute @s[scores={wbef=235}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有235秒"}]}
execute @s[scores={wbef=234}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有234秒"}]}
execute @s[scores={wbef=233}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有233秒"}]}
execute @s[scores={wbef=232}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有232秒"}]}
execute @s[scores={wbef=231}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有231秒"}]}
execute @s[scores={wbef=230}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有230秒"}]}
execute @s[scores={wbef=229}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有229秒"}]}
execute @s[scores={wbef=228}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有228秒"}]}
execute @s[scores={wbef=227}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有227秒"}]}
execute @s[scores={wbef=226}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有226秒"}]}
execute @s[scores={wbef=225}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有225秒"}]}
execute @s[scores={wbef=224}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有224秒"}]}
execute @s[scores={wbef=223}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有223秒"}]}
execute @s[scores={wbef=222}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有222秒"}]}
execute @s[scores={wbef=221}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有221秒"}]}
execute @s[scores={wbef=220}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有220秒"}]}
execute @s[scores={wbef=219}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有219秒"}]}
execute @s[scores={wbef=218}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有218秒"}]}
execute @s[scores={wbef=217}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有217秒"}]}
execute @s[scores={wbef=216}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有216秒"}]}
execute @s[scores={wbef=215}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有215秒"}]}
execute @s[scores={wbef=214}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有214秒"}]}
execute @s[scores={wbef=213}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有213秒"}]}
execute @s[scores={wbef=212}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有212秒"}]}
execute @s[scores={wbef=211}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有211秒"}]}
execute @s[scores={wbef=210}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有210秒"}]}
execute @s[scores={wbef=209}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有209秒"}]}
execute @s[scores={wbef=208}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有208秒"}]}
execute @s[scores={wbef=207}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有207秒"}]}
execute @s[scores={wbef=206}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有206秒"}]}
execute @s[scores={wbef=205}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有205秒"}]}
execute @s[scores={wbef=204}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有204秒"}]}
execute @s[scores={wbef=203}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有203秒"}]}
execute @s[scores={wbef=202}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有202秒"}]}
execute @s[scores={wbef=201}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有201秒"}]}
execute @s[scores={wbef=200}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有200秒"}]}
execute @s[scores={wbef=199}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有199秒"}]}
execute @s[scores={wbef=198}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有198秒"}]}
execute @s[scores={wbef=197}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有197秒"}]}
execute @s[scores={wbef=196}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有196秒"}]}
execute @s[scores={wbef=195}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有195秒"}]}
execute @s[scores={wbef=194}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有194秒"}]}
execute @s[scores={wbef=193}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有193秒"}]}
execute @s[scores={wbef=192}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有192秒"}]}
execute @s[scores={wbef=191}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有191秒"}]}
execute @s[scores={wbef=190}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有190秒"}]}
execute @s[scores={wbef=189}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有189秒"}]}
execute @s[scores={wbef=188}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有188秒"}]}
execute @s[scores={wbef=187}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有187秒"}]}
execute @s[scores={wbef=186}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有186秒"}]}
execute @s[scores={wbef=185}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有185秒"}]}
execute @s[scores={wbef=184}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有184秒"}]}
execute @s[scores={wbef=183}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有183秒"}]}
execute @s[scores={wbef=182}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有182秒"}]}
execute @s[scores={wbef=181}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有181秒"}]}
execute @s[scores={wbef=180}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有180秒"}]}
execute @s[scores={wbef=179}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有179秒"}]}
execute @s[scores={wbef=178}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有178秒"}]}
execute @s[scores={wbef=177}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有177秒"}]}
execute @s[scores={wbef=176}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有176秒"}]}
execute @s[scores={wbef=175}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有175秒"}]}
execute @s[scores={wbef=174}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有174秒"}]}
execute @s[scores={wbef=173}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有173秒"}]}
execute @s[scores={wbef=172}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有172秒"}]}
execute @s[scores={wbef=171}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有171秒"}]}
execute @s[scores={wbef=170}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有170秒"}]}
execute @s[scores={wbef=169}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有169秒"}]}
execute @s[scores={wbef=168}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有168秒"}]}
execute @s[scores={wbef=167}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有167秒"}]}
execute @s[scores={wbef=166}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有166秒"}]}
execute @s[scores={wbef=165}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有165秒"}]}
execute @s[scores={wbef=164}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有164秒"}]}
execute @s[scores={wbef=163}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有163秒"}]}
execute @s[scores={wbef=162}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有162秒"}]}
execute @s[scores={wbef=161}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有161秒"}]}
execute @s[scores={wbef=160}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有160秒"}]}
execute @s[scores={wbef=159}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有159秒"}]}
execute @s[scores={wbef=158}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有158秒"}]}
execute @s[scores={wbef=157}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有157秒"}]}
execute @s[scores={wbef=156}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有156秒"}]}
execute @s[scores={wbef=155}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有155秒"}]}
execute @s[scores={wbef=154}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有154秒"}]}
execute @s[scores={wbef=153}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有153秒"}]}
execute @s[scores={wbef=152}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有152秒"}]}
execute @s[scores={wbef=151}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有151秒"}]}
execute @s[scores={wbef=150}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有150秒"}]}
execute @s[scores={wbef=149}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有149秒"}]}
execute @s[scores={wbef=148}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有148秒"}]}
execute @s[scores={wbef=147}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有147秒"}]}
execute @s[scores={wbef=146}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有146秒"}]}
execute @s[scores={wbef=145}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有145秒"}]}
execute @s[scores={wbef=144}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有144秒"}]}
execute @s[scores={wbef=143}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有143秒"}]}
execute @s[scores={wbef=142}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有142秒"}]}
execute @s[scores={wbef=141}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有141秒"}]}
execute @s[scores={wbef=140}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有140秒"}]}
execute @s[scores={wbef=139}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有139秒"}]}
execute @s[scores={wbef=138}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有138秒"}]}
execute @s[scores={wbef=137}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有137秒"}]}
execute @s[scores={wbef=136}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有136秒"}]}
execute @s[scores={wbef=135}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有135秒"}]}
execute @s[scores={wbef=134}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有134秒"}]}
execute @s[scores={wbef=133}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有133秒"}]}
execute @s[scores={wbef=132}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有132秒"}]}
execute @s[scores={wbef=131}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有131秒"}]}
execute @s[scores={wbef=130}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有130秒"}]}
execute @s[scores={wbef=129}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有129秒"}]}
execute @s[scores={wbef=128}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有128秒"}]}
execute @s[scores={wbef=127}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有127秒"}]}
execute @s[scores={wbef=126}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有126秒"}]}
execute @s[scores={wbef=125}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有125秒"}]}
execute @s[scores={wbef=124}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有124秒"}]}
execute @s[scores={wbef=123}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有123秒"}]}
execute @s[scores={wbef=122}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有122秒"}]}
execute @s[scores={wbef=121}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有121秒"}]}
execute @s[scores={wbef=120}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有120秒"}]}
execute @s[scores={wbef=119}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有119秒"}]}
execute @s[scores={wbef=118}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有118秒"}]}
execute @s[scores={wbef=117}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有117秒"}]}
execute @s[scores={wbef=116}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有116秒"}]}
execute @s[scores={wbef=115}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有115秒"}]}
execute @s[scores={wbef=114}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有114秒"}]}
execute @s[scores={wbef=113}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有113秒"}]}
execute @s[scores={wbef=112}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有112秒"}]}
execute @s[scores={wbef=111}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有111秒"}]}
execute @s[scores={wbef=110}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有110秒"}]}
execute @s[scores={wbef=109}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有109秒"}]}
execute @s[scores={wbef=108}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有108秒"}]}
execute @s[scores={wbef=107}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有107秒"}]}
execute @s[scores={wbef=106}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有106秒"}]}
execute @s[scores={wbef=105}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有105秒"}]}
execute @s[scores={wbef=104}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有104秒"}]}
execute @s[scores={wbef=103}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有103秒"}]}
execute @s[scores={wbef=102}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有102秒"}]}
execute @s[scores={wbef=101}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有101秒"}]}
execute @s[scores={wbef=100}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有100秒"}]}
execute @s[scores={wbef=99}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有99秒"}]}
execute @s[scores={wbef=98}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有98秒"}]}
execute @s[scores={wbef=97}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有97秒"}]}
execute @s[scores={wbef=96}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有96秒"}]}
execute @s[scores={wbef=95}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有95秒"}]}
execute @s[scores={wbef=94}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有94秒"}]}
execute @s[scores={wbef=93}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有93秒"}]}
execute @s[scores={wbef=92}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有92秒"}]}
execute @s[scores={wbef=91}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有91秒"}]}
execute @s[scores={wbef=90}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有90秒"}]}
execute @s[scores={wbef=89}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有89秒"}]}
execute @s[scores={wbef=88}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有88秒"}]}
execute @s[scores={wbef=87}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有87秒"}]}
execute @s[scores={wbef=86}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有86秒"}]}
execute @s[scores={wbef=85}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有85秒"}]}
execute @s[scores={wbef=84}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有84秒"}]}
execute @s[scores={wbef=83}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有83秒"}]}
execute @s[scores={wbef=82}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有82秒"}]}
execute @s[scores={wbef=81}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有81秒"}]}
execute @s[scores={wbef=80}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有80秒"}]}
execute @s[scores={wbef=79}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有79秒"}]}
execute @s[scores={wbef=78}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有78秒"}]}
execute @s[scores={wbef=77}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有77秒"}]}
execute @s[scores={wbef=76}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有76秒"}]}
execute @s[scores={wbef=75}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有75秒"}]}
execute @s[scores={wbef=74}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有74秒"}]}
execute @s[scores={wbef=73}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有73秒"}]}
execute @s[scores={wbef=72}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有72秒"}]}
execute @s[scores={wbef=71}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有71秒"}]}
execute @s[scores={wbef=70}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有70秒"}]}
execute @s[scores={wbef=69}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有69秒"}]}
execute @s[scores={wbef=68}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有68秒"}]}
execute @s[scores={wbef=67}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有67秒"}]}
execute @s[scores={wbef=66}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有66秒"}]}
execute @s[scores={wbef=65}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有65秒"}]}
execute @s[scores={wbef=64}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有64秒"}]}
execute @s[scores={wbef=63}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有63秒"}]}
execute @s[scores={wbef=62}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有62秒"}]}
execute @s[scores={wbef=61}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有61秒"}]}
execute @s[scores={wbef=60}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有60秒"}]}
execute @s[scores={wbef=59}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有59秒"}]}
execute @s[scores={wbef=58}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有58秒"}]}
execute @s[scores={wbef=57}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有57秒"}]}
execute @s[scores={wbef=56}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有56秒"}]}
execute @s[scores={wbef=55}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有55秒"}]}
execute @s[scores={wbef=54}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有54秒"}]}
execute @s[scores={wbef=53}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有53秒"}]}
execute @s[scores={wbef=52}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有52秒"}]}
execute @s[scores={wbef=51}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有51秒"}]}
execute @s[scores={wbef=50}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有50秒"}]}
execute @s[scores={wbef=49}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有49秒"}]}
execute @s[scores={wbef=48}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有48秒"}]}
execute @s[scores={wbef=47}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有47秒"}]}
execute @s[scores={wbef=46}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有46秒"}]}
execute @s[scores={wbef=45}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有45秒"}]}
execute @s[scores={wbef=44}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有44秒"}]}
execute @s[scores={wbef=43}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有43秒"}]}
execute @s[scores={wbef=42}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有42秒"}]}
execute @s[scores={wbef=41}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有41秒"}]}
execute @s[scores={wbef=40}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有40秒"}]}
execute @s[scores={wbef=39}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有39秒"}]}
execute @s[scores={wbef=38}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有38秒"}]}
execute @s[scores={wbef=37}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有37秒"}]}
execute @s[scores={wbef=36}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有36秒"}]}
execute @s[scores={wbef=35}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有35秒"}]}
execute @s[scores={wbef=34}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有34秒"}]}
execute @s[scores={wbef=33}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有33秒"}]}
execute @s[scores={wbef=32}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有32秒"}]}
execute @s[scores={wbef=31}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有31秒"}]}
execute @s[scores={wbef=30}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有30秒"}]}
execute @s[scores={wbef=29}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有29秒"}]}
execute @s[scores={wbef=28}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有28秒"}]}
execute @s[scores={wbef=27}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有27秒"}]}
execute @s[scores={wbef=26}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有26秒"}]}
execute @s[scores={wbef=25}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有25秒"}]}
execute @s[scores={wbef=24}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有24秒"}]}
execute @s[scores={wbef=23}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有23秒"}]}
execute @s[scores={wbef=22}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有22秒"}]}
execute @s[scores={wbef=21}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有21秒"}]}
execute @s[scores={wbef=20}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有20秒"}]}
execute @s[scores={wbef=19}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有19秒"}]}
execute @s[scores={wbef=18}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有18秒"}]}
execute @s[scores={wbef=17}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有17秒"}]}
execute @s[scores={wbef=16}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有16秒"}]}
execute @s[scores={wbef=15}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有15秒"}]}
execute @s[scores={wbef=14}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有14秒"}]}
execute @s[scores={wbef=13}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有13秒"}]}
execute @s[scores={wbef=12}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有12秒"}]}
execute @s[scores={wbef=11}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有11秒"}]}
execute @s[scores={wbef=10}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有10秒"}]}
execute @s[scores={wbef=9}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有9秒"}]}
execute @s[scores={wbef=8}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有8秒"}]}
execute @s[scores={wbef=7}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有7秒"}]}
execute @s[scores={wbef=6}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有6秒"}]}
execute @s[scores={wbef=5}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有5秒"}]}
execute @s[scores={wbef=4}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有4秒"}]}
execute @s[scores={wbef=3}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有3秒"}]}
execute @s[scores={wbef=2}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有2秒"}]}
execute @s[scores={wbef=1}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§b[系统]勇者之力冷却中，还有1秒"}]}