execute as @s[scores={wbdjjf=900..,wbdj=0}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=2100..,wbdj=1}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=3600..,wbdj=2}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=5400..,wbdj=3}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=7500..,wbdj=4}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=9900..,wbdj=5}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=12600..,wbdj=6}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=15600..,wbdj=7}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=18900..,wbdj=8}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=22500..,wbdj=9}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=26400..,wbdj=10}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=30600..,wbdj=11}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=35100..,wbdj=12}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=39900..,wbdj=13}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=45000..,wbdj=14}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=50400..,wbdj=15}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=56100..,wbdj=16}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=62100..,wbdj=17}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=68400..,wbdj=18}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=75000..,wbdj=19}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=81900..,wbdj=20}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=89100..,wbdj=21}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=96600..,wbdj=22}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=104400..,wbdj=23}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=112500..,wbdj=24}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=120900..,wbdj=25}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=129600..,wbdj=26}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=138600..,wbdj=27}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=147900..,wbdj=28}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=157500..,wbdj=29}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=167400..,wbdj=30}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=177600..,wbdj=31}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=188100..,wbdj=32}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=198900..,wbdj=33}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=210000..,wbdj=34}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=221400..,wbdj=35}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=233100..,wbdj=36}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=245100..,wbdj=37}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=257400..,wbdj=38}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=270000..,wbdj=39}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=282900..,wbdj=40}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=296100..,wbdj=41}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=309600..,wbdj=42}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=323400..,wbdj=43}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=337500..,wbdj=44}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=351900..,wbdj=45}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=366600..,wbdj=46}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=381600..,wbdj=47}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=396900..,wbdj=48}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=412500..,wbdj=49}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=428400..,wbdj=50}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=444600..,wbdj=51}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=461100..,wbdj=52}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=477900..,wbdj=53}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=495000..,wbdj=54}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=512400..,wbdj=55}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=530100..,wbdj=56}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=548100..,wbdj=57}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=566400..,wbdj=58}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=585000..,wbdj=59}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=603900..,wbdj=60}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=623100..,wbdj=61}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=642600..,wbdj=62}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=662400..,wbdj=63}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=682500..,wbdj=64}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=702900..,wbdj=65}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=723600..,wbdj=66}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=744600..,wbdj=67}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=765900..,wbdj=68}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=787500..,wbdj=69}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=809400..,wbdj=70}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=831600..,wbdj=71}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=854100..,wbdj=72}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=876900..,wbdj=73}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=900000..,wbdj=74}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=923400..,wbdj=75}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=947100..,wbdj=76}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=971100..,wbdj=77}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=995400..,wbdj=78}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1020000..,wbdj=79}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1044900..,wbdj=80}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1070100..,wbdj=81}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1095600..,wbdj=82}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1121400..,wbdj=83}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1147500..,wbdj=84}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1173900..,wbdj=85}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1200600..,wbdj=86}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1227600..,wbdj=87}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1254900..,wbdj=88}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1282500..,wbdj=89}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1310400..,wbdj=90}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1338600..,wbdj=91}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1367100..,wbdj=92}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1395900..,wbdj=93}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1425000..,wbdj=94}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1454400..,wbdj=95}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1484100..,wbdj=96}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1514100..,wbdj=97}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1544400..,wbdj=98}] at @s run scoreboard players add @s wbdj 1
execute as @s[scores={wbdjjf=1575000..,wbdj=99}] at @s run scoreboard players add @s wbdj 1